#!/usr/bin/env python3
from pathlib import Path

def make_link(path: Path, base: Path) -> str:
    rel = path.relative_to(base)
    return '<li><a href="%s">%s</a></li>' % (rel.as_posix(), rel.as_posix())

base = Path(__file__).resolve().parents[1]
out_dir = base / 'DOCS'
out_dir.mkdir(exist_ok=True)
entries = []

# Top-level doc files
for name in sorted([
    'README.md','README.full.md','README.deploy.md','INDEX.md','CHANGELOG.md',
    'RUNBOOK.md','DEVELOPER.md','CONTRIBUTING.md','SECURITY.md','API_EXAMPLES.md'
]):
    p = base / name
    if p.exists():
        entries.append(make_link(p, base))

# DOCS/ subfolder
docs_folder = base / 'DOCS'
if docs_folder.exists():
    docs_entries = []
    for p in sorted(docs_folder.rglob('*.md')):
        docs_entries.append(make_link(p, base))
    if docs_entries:
        entries.append('<h2>DOCS/</h2>')
        entries.extend(docs_entries)

# app/ markdown files
app_docs = []
for p in sorted((base / 'app').rglob('*.md')):
    app_docs.append(make_link(p, base))
if app_docs:
    entries.append('<h2>app/</h2>')
    entries.extend(app_docs)

html_parts = [
    '<!doctype html>',
    '<html>',
    '<head>',
    '  <meta charset="utf-8">',
    '  <title>Documentation Index</title>',
    '  <style>body{font-family:Arial,Helvetica,sans-serif;margin:40px;}li{margin:6px 0}</style>',
    '</head>',
    '<body>',
    '  <h1>Documentation Index</h1>',
    '  <p>Generated index of documentation files in this repository.</p>',
    '  <ul>',
]

html_parts.append('\n    '.join(entries))

html_parts.extend([
    '  </ul>',
    '  <hr>',
    '  <p>Generated by <code>scripts/generate_docs_index.py</code></p>',
    '</body>',
    '</html>',
])

html = '\n'.join(html_parts)

(out_dir / 'index.html').write_text(html, encoding='utf-8')
print('Wrote', out_dir / 'index.html')
